export const SITE_NAME = "ChinaUniMatch";
export const SITE_TAGLINE = "Your gateway to Chinese universities";
export const SITE_DESCRIPTION =
  "Discover, compare, and apply to top Chinese universities. Find scholarships, compare tuition costs, and get step-by-step application guidance.";
export const WHATSAPP_NUMBER = "+21228345297";
export const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER.replace(/\D/g, "")}`;

export const FIELDS_OF_STUDY = [
  "Engineering",
  "Medicine",
  "Business",
  "Science",
  "Arts & Humanities",
  "Law",
  "Agriculture",
  "Computer Science",
  "Economics",
  "Education",
  "Architecture",
  "Environmental Science",
  "Chinese Language",
  "International Relations",
  "Media & Communication",
];

export const CHINESE_PROVINCES = [
  "Beijing",
  "Shanghai",
  "Tianjin",
  "Chongqing",
  "Guangdong",
  "Zhejiang",
  "Jiangsu",
  "Shandong",
  "Sichuan",
  "Hubei",
  "Hunan",
  "Fujian",
  "Liaoning",
  "Shaanxi",
  "Henan",
  "Heilongjiang",
  "Jilin",
  "Hebei",
  "Shanxi",
  "Anhui",
  "Jiangxi",
  "Guangxi",
  "Yunnan",
  "Guizhou",
  "Gansu",
  "Hainan",
  "Nei Mongol",
  "Xinjiang",
  "Ningxia",
  "Qinghai",
  "Tibet",
];

/** All cities from the 2024-2025 Ministry of Education distribution, sorted by university count */
export const CHINESE_CITIES: { city: string; count: number }[] = [
  { city: "Beijing",      count: 92 },
  { city: "Wuhan",        count: 83 },
  { city: "Guangzhou",    count: 83 },
  { city: "Shanghai",     count: 68 },
  { city: "Zhengzhou",    count: 67 },
  { city: "Chongqing",    count: 65 },
  { city: "Xi'an",        count: 63 },
  { city: "Chengdu",      count: 58 },
  { city: "Tianjin",      count: 57 },
  { city: "Hefei",        count: 54 },
  { city: "Nanchang",     count: 54 },
  { city: "Nanjing",      count: 53 },
  { city: "Changsha",     count: 52 },
  { city: "Harbin",       count: 51 },
  { city: "Hangzhou",     count: 47 },
  { city: "Shenyang",     count: 45 },
  { city: "Kunming",      count: 45 },
  { city: "Shijiazhuang", count: 44 },
  { city: "Jinan",        count: 43 },
  { city: "Taiyuan",      count: 41 },
  { city: "Fuzhou",       count: 36 },
  { city: "Guiyang",      count: 35 },
  { city: "Nanning",      count: 35 },
  { city: "Lanzhou",      count: 30 },
  { city: "Dalian",       count: 30 },
  { city: "Suzhou",       count: 26 },
  { city: "Urumqi",       count: 26 },
  { city: "Qingdao",      count: 25 },
  { city: "Hohhot",       count: 24 },
  { city: "Yinchuan",     count: 18 },
  { city: "Xiamen",       count: 16 },
  { city: "Ningbo",       count: 15 },
  { city: "Shenzhen",     count: 14 },
  { city: "Haikou",       count: 13 },
  { city: "Xining",       count: 12 },
  { city: "Wuxi",         count: 12 },
  { city: "Xuzhou",       count: 12 },
  { city: "Changzhou",    count: 11 },
  { city: "Wenzhou",      count: 11 },
  { city: "Lhasa",        count:  7 },
];

export const NAV_LINKS = [
  { label: "Discover", href: "/discover" },
  { label: "Compare", href: "/compare" },
  { label: "Scholarships", href: "/scholarships" },
  { label: "Apply", href: "/apply" },
];
