/**
 * Mock program data — used when Supabase is not connected.
 * Replace with real data by running the data pipeline:
 *   python tools/scrape_scholarshipchina.py && python tools/normalize_program_data.py && python tools/export_to_data.py
 */

import type { Program } from "@/types";

export const MOCK_PROGRAMS: Program[] = [
  {
    id: "mock-pku-cs-bachelor",
    universityId: "mock-pku",
    programCode: "PKU-CS-25",
    field: "Computer Science",
    programName: "Computer Science and Technology",
    degree: "BACHELOR",
    teachingLanguage: "ENGLISH",
    intakeSeason: "September",
    intakeYear: 2025,
    applicationDeadline: "2025-05-30",
    programDuration: "4 years",
    originalTuition: 30000,
    tuitionAfterScholarship: 15000,
    accommodationFee: 8000,
    accommodationSingleFee: 10000,
    accommodationDoubleFee: 6000,
    registrationFee: 800,
    minAge: 18,
    maxAge: 35,
    acceptsMinors: false,
    hasCscaScore: false,
    locationRestrictions: [],
    minGpaScore: 70,
    minIeltsScore: 6.0,
    requiresPassportPhoto: true,
    requiresPassportId: true,
    requiresTranscripts: true,
    requiresHighestDegree: true,
    requiresPhysicalExam: true,
    requiresNonCriminalRecord: true,
    requiresEnglishCert: true,
    requiresApplicationForm: true,
    requiresStudyPlan: true,
    requiresRecommendations: true,
    recommendationLetterCount: 2,
    university: {
      id: "mock-pku",
      name: "Peking University",
      nameZh: "北京大学",
      slug: "peking-university",
      city: "Beijing",
      province: "Beijing",
      ranking: 1,
      website: "https://www.pku.edu.cn",
      description: "Peking University is China's top research university, consistently ranked among the best in Asia and the world.",
    },
    scholarships: [
      {
        id: "mock-pku-scholarship-1",
        programId: "mock-pku-cs-bachelor",
        type: "UNIVERSITY",
        name: "PKU International Student Merit Scholarship",
        category: "Partial",
        duration: "4 years (renewable)",
        coversTuition: false,
        policyDetails: "50% tuition waiver for academically outstanding international students. Renewed annually based on GPA above 85%.",
      },
    ],
  },
  {
    id: "mock-fudan-mba-master",
    universityId: "mock-fudan",
    programCode: "FDN-MBA-25",
    field: "Business",
    programName: "Master of Business Administration (MBA)",
    degree: "MASTER",
    teachingLanguage: "ENGLISH",
    intakeSeason: "September",
    intakeYear: 2025,
    applicationDeadline: "2025-04-15",
    programDuration: "2 years",
    originalTuition: 80000,
    tuitionAfterScholarship: 0,
    accommodationFee: 10000,
    accommodationSingleFee: 12000,
    accommodationDoubleFee: 8000,
    registrationFee: 800,
    minAge: 22,
    maxAge: 40,
    acceptsMinors: false,
    hasCscaScore: false,
    locationRestrictions: [],
    minGpaScore: 75,
    minIeltsScore: 6.5,
    minToeflScore: 90,
    requiresPassportPhoto: true,
    requiresPassportId: true,
    requiresTranscripts: true,
    requiresHighestDegree: true,
    requiresPhysicalExam: true,
    requiresNonCriminalRecord: true,
    requiresEnglishCert: true,
    requiresApplicationForm: true,
    requiresStudyPlan: true,
    requiresRecommendations: true,
    recommendationLetterCount: 2,
    university: {
      id: "mock-fudan",
      name: "Fudan University",
      nameZh: "复旦大学",
      slug: "fudan-university",
      city: "Shanghai",
      province: "Shanghai",
      ranking: 4,
      website: "https://www.fudan.edu.cn",
      description: "Fudan University is one of China's most prestigious universities, located in Shanghai, with world-class business and medical schools.",
    },
    scholarships: [
      {
        id: "mock-fudan-csc",
        programId: "mock-fudan-mba-master",
        type: "CSC",
        name: "Chinese Government Scholarship (CSC)",
        category: "Full",
        duration: "2 years",
        coversTuition: true,
        livingAllowance: 3000,
        policyDetails: "Full tuition waiver + ¥3,000/month living stipend + accommodation. Covers registration and insurance fees.",
      },
    ],
  },
  {
    id: "mock-tsinghua-ee-phd",
    universityId: "mock-tsinghua",
    programCode: "THU-EE-25",
    field: "Engineering",
    programName: "Electrical Engineering (PhD)",
    degree: "DOCTORAL",
    teachingLanguage: "ENGLISH",
    intakeSeason: "September",
    intakeYear: 2025,
    applicationDeadline: "2025-03-31",
    programDuration: "4 years",
    originalTuition: 35000,
    tuitionAfterScholarship: 0,
    accommodationFee: 8000,
    registrationFee: 800,
    minAge: 22,
    maxAge: 40,
    acceptsMinors: false,
    hasCscaScore: false,
    locationRestrictions: [],
    minGpaScore: 80,
    minIeltsScore: 6.5,
    minToeflScore: 90,
    requiresPassportPhoto: true,
    requiresPassportId: true,
    requiresTranscripts: true,
    requiresHighestDegree: true,
    requiresPhysicalExam: true,
    requiresNonCriminalRecord: true,
    requiresEnglishCert: true,
    requiresApplicationForm: true,
    requiresStudyPlan: true,
    requiresRecommendations: true,
    recommendationLetterCount: 2,
    university: {
      id: "mock-tsinghua",
      name: "Tsinghua University",
      nameZh: "清华大学",
      slug: "tsinghua-university",
      city: "Beijing",
      province: "Beijing",
      ranking: 2,
      website: "https://www.tsinghua.edu.cn",
      description: "Tsinghua University is China's leading science and technology university, renowned globally for engineering and research.",
    },
    scholarships: [
      {
        id: "mock-tsinghua-csc",
        programId: "mock-tsinghua-ee-phd",
        type: "CSC",
        name: "Chinese Government Scholarship (CSC)",
        category: "Full",
        duration: "4 years",
        coversTuition: true,
        livingAllowance: 3500,
        policyDetails: "Full tuition waiver + ¥3,500/month stipend for doctoral students. Includes accommodation and medical insurance.",
      },
    ],
  },
  {
    id: "mock-zju-medicine-bachelor",
    universityId: "mock-zju",
    programCode: "ZJU-MED-25",
    field: "Medicine",
    programName: "Clinical Medicine (MBBS)",
    degree: "BACHELOR",
    teachingLanguage: "ENGLISH",
    intakeSeason: "September",
    intakeYear: 2025,
    applicationDeadline: "2025-06-30",
    programDuration: "6 years",
    originalTuition: 45000,
    accommodationFee: 9000,
    accommodationSingleFee: 11000,
    accommodationDoubleFee: 7000,
    registrationFee: 800,
    minAge: 18,
    maxAge: 30,
    acceptsMinors: false,
    hasCscaScore: false,
    locationRestrictions: [],
    minGpaScore: 75,
    minIeltsScore: 6.0,
    requiresPassportPhoto: true,
    requiresPassportId: true,
    requiresTranscripts: true,
    requiresHighestDegree: true,
    requiresPhysicalExam: true,
    requiresNonCriminalRecord: true,
    requiresEnglishCert: true,
    requiresApplicationForm: true,
    requiresStudyPlan: true,
    requiresRecommendations: false,
    recommendationLetterCount: 0,
    university: {
      id: "mock-zju",
      name: "Zhejiang University",
      nameZh: "浙江大学",
      slug: "zhejiang-university",
      city: "Hangzhou",
      province: "Zhejiang",
      ranking: 3,
      website: "https://www.zju.edu.cn",
      description: "Zhejiang University is one of China's top comprehensive universities, known for medicine, engineering, and agriculture.",
    },
    scholarships: [],
  },
  {
    id: "mock-sjtu-ai-master",
    universityId: "mock-sjtu",
    programCode: "SJTU-AI-25",
    field: "Computer Science",
    programName: "Artificial Intelligence",
    degree: "MASTER",
    teachingLanguage: "ENGLISH",
    intakeSeason: "September",
    intakeYear: 2025,
    applicationDeadline: "2025-05-15",
    programDuration: "2.5 years",
    originalTuition: 40000,
    tuitionAfterScholarship: 20000,
    accommodationFee: 9000,
    accommodationSingleFee: 11000,
    accommodationDoubleFee: 7000,
    registrationFee: 800,
    minAge: 22,
    maxAge: 35,
    acceptsMinors: false,
    hasCscaScore: false,
    locationRestrictions: [],
    minGpaScore: 75,
    minIeltsScore: 6.0,
    minToeflScore: 85,
    requiresPassportPhoto: true,
    requiresPassportId: true,
    requiresTranscripts: true,
    requiresHighestDegree: true,
    requiresPhysicalExam: true,
    requiresNonCriminalRecord: true,
    requiresEnglishCert: true,
    requiresApplicationForm: true,
    requiresStudyPlan: true,
    requiresRecommendations: true,
    recommendationLetterCount: 2,
    university: {
      id: "mock-sjtu",
      name: "Shanghai Jiao Tong University",
      nameZh: "上海交通大学",
      slug: "shanghai-jiao-tong-university",
      city: "Shanghai",
      province: "Shanghai",
      ranking: 5,
      website: "https://www.sjtu.edu.cn",
      description: "SJTU is a leading research university in Shanghai, renowned for engineering, medicine, and cutting-edge AI research.",
    },
    scholarships: [
      {
        id: "mock-sjtu-scholarship",
        programId: "mock-sjtu-ai-master",
        type: "UNIVERSITY",
        name: "SJTU Excellence Scholarship",
        category: "Partial",
        duration: "2.5 years",
        coversTuition: false,
        livingAllowance: 2000,
        policyDetails: "50% tuition reduction + ¥2,000/month stipend. Awarded to top 30% of admitted students based on academic record.",
      },
    ],
  },
  {
    id: "mock-whu-law-master",
    universityId: "mock-whu",
    programCode: "WHU-LAW-25",
    field: "Law",
    programName: "International Law (LLM)",
    degree: "MASTER",
    teachingLanguage: "ENGLISH",
    intakeSeason: "September",
    intakeYear: 2025,
    applicationDeadline: "2025-05-01",
    programDuration: "2 years",
    originalTuition: 32000,
    tuitionAfterScholarship: 0,
    accommodationFee: 7000,
    accommodationSingleFee: 9000,
    accommodationDoubleFee: 5500,
    registrationFee: 800,
    minAge: 22,
    maxAge: 45,
    acceptsMinors: false,
    hasCscaScore: false,
    locationRestrictions: [],
    minGpaScore: 70,
    minIeltsScore: 6.0,
    requiresPassportPhoto: true,
    requiresPassportId: true,
    requiresTranscripts: true,
    requiresHighestDegree: true,
    requiresPhysicalExam: true,
    requiresNonCriminalRecord: true,
    requiresEnglishCert: true,
    requiresApplicationForm: true,
    requiresStudyPlan: true,
    requiresRecommendations: true,
    recommendationLetterCount: 2,
    university: {
      id: "mock-whu",
      name: "Wuhan University",
      nameZh: "武汉大学",
      slug: "wuhan-university",
      city: "Wuhan",
      province: "Hubei",
      ranking: 6,
      website: "https://www.whu.edu.cn",
      description: "Wuhan University is one of the oldest universities with strong law and humanities programs.",
    },
    scholarships: [
      {
        id: "mock-whu-scholarship",
        programId: "mock-whu-law-master",
        type: "PROVINCIAL",
        name: "Hubei Provincial Government Scholarship",
        category: "Full",
        duration: "2 years",
        coversTuition: true,
        livingAllowance: 1500,
        policyDetails: "Full tuition coverage + ¥1,500/month living allowance. Applicants must apply through the Hubei Education Department.",
      },
    ],
  },
];
